name: jobportal
description: A new Flutter project.
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fast_flutter_driver_tool: ^3.0.0

 
  

  mongo_dart: ^0.9.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  http: ^0.13.6
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  build_runner: ^2.0.4
  
  flutter_secure_storage: ^8.0.0
  go_router: ^7.1.1
  sqflite: ^2.2.8+4
  path: ^1.8.3
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  mockito: ^5.0.0
 
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  json_serializable: ^6.6.0
  #integration_test: ^1.0.1


  flutter_lints: ^2.0.0
  bloc_test: ^9.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

